### ISSUE TITLE
cpe://o returned insted of cpe://a for each services

### ISSUE THREAD

**Issue by ivanarielcaceres** [johanlundberg/python-nmap#1]
When scanning ports, the SSh returns the cpe: //o instead of cpe: //a.
It only happens with ssh, the rest is ok.
Is there any way to get it?
When scanning from the terminal, it brings both, but when scanning from python, it only brings the first one.
Thanks in advance!

**Comment by johanlundberg** [comment]
This repo is just a personal clone of the actual project python-nmap repo located here: https://bitbucket.org/xael/python-nmap.
